---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Azure Portal:
        - icon: azure.png
          href: https://portal.azure.com/
    - Quickref Me:
        - icon: https://quickref.me/images/favicon.png?v=1
          href: https://cheatsheets.zip/

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/

- Useful Repos:
    - Homepage:
        - icon: homepage.png
          href: https://github.com/gethomepage/homepage
    - Headscale:
        - icon: tailscale.png
          href: https://github.com/juanfont/headscale
