---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Gaming:
    - TableTop:
        href: https://tabletop.{{HOMEPAGE_VAR_DOMAINENAME}}
        description : Tabletop application
        icon: https://tabletop.{{HOMEPAGE_VAR_DOMAINENAME}}/icons/vtt-512.png
        siteMonitor: https://tabletop.{{HOMEPAGE_VAR_DOMAINENAME}}
        widget:
            type: customapi
            url: https://tabletop.{{HOMEPAGE_VAR_DOMAINENAME}}/api/status
            refreshInterval: 10000
            method: GET
            mappings:
                - field: system
                  label: System
                  format: text
                - field: users
                  label: Users
                  format: number
                - field: world
                  label: World
                  format: text
    - Minecraft Asylium:
        icon: minecraft.png
        description: Minecraft server
        widget:
            type: minecraft
            url: udp://asylium.omgcraft.fr

- VPN:
    - Headscale:
       widgets:
            - type: headscale
              url: https://headscale.{{HOMEPAGE_VAR_DOMAINENAME}}
              nodeId: 1
              key: {{HOMEPAGE_FILE_HEADSCALE_SECRET}}
              id: test
            - type: headscale
              url: https://headscale.{{HOMEPAGE_VAR_DOMAINENAME}}
              nodeId: 3
              key: {{HOMEPAGE_FILE_HEADSCALE_SECRET}}

            - type: headscale
              url: https://headscale.{{HOMEPAGE_VAR_DOMAINENAME}}
              nodeId: 13
              key: {{HOMEPAGE_FILE_HEADSCALE_SECRET}}
            - type: headscale
              url: https://headscale.{{HOMEPAGE_VAR_DOMAINENAME}}
              nodeId: 9
              key: {{HOMEPAGE_FILE_HEADSCALE_SECRET}}   
            - type: headscale
              url: https://headscale.{{HOMEPAGE_VAR_DOMAINENAME}}
              nodeId: 10
              key: {{HOMEPAGE_FILE_HEADSCALE_SECRET}}
- Calendar:
    - My Calendar:
        widget:
          type: calendar
          maxEvents: 100
          showTime: true
          timezone: Europe/Paris
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/elwanlefevre.51%40gmail.com/private-e4cd5cfffa9769b26eff301bbf9c07bd/basic.ics
              name: perso
              color: blue
              params:
                showName: true