services:
  asylium-discord-bot:
    image: furiell/asylium_discordbot:latest
    container_name: asylium-discord-bot
    security_opt:
    - no-new-privileges:true
    restart: unless-stopped
    profiles: ["discord_bot", "all", "asylium-discord-bot"]
    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      TOKEN: $DISCORD_BOT_TOKEN
    labels:
      - homepage.group=Discord Bot
      - homepage.description=Asylium Discord Bot
      - homepage.name=Asylium Discord Bot
      - homepage.icon=discord.png