services:
  meilisearch_barassistant:
    image: getmeili/meilisearch:v1.9 # Never use latest tag
    container_name: meilisearch_barassistant
    restart: unless-stopped
    profiles: ["barassistant", "all"]
    networks:
      t_proxy:
      bar_network:
    volumes:
      - meilisearch_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    #labels:
      # Traefik labels
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.meilisearch-rtr.entrypoints=websecure"
      - "traefik.http.routers.meilisearch-rtr.rule=Host(`$URI_MEILISEARCH.$DOMAINNAME_1`)"
      - "traefik.http.routers.meilisearch-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.meilisearch-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.meilisearch-rtr.service=meilisearch-svc"
      - "traefik.http.services.meilisearch-svc.loadbalancer.server.port=7700"

  bar-assistant:
    image: barassistant/server:v4
    container_name: bar-assistant
    restart: unless-stopped
    profiles: ["barassistant", "all"]
    networks:
      t_proxy:
      bar_network:
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant
    depends_on:
      - meilisearch_barassistant
      # - redis_barassistant # Remove if not using redis
    environment:
      - APP_URL=https://$URI_BARAPI.$DOMAINNAME_1
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch_barassistant:7700 # This needs to be host that can be resolved from inside the container.
      # - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=file #redis # Change to "file" if not using redis
      - SESSION_DRIVER=file #redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    #labels:
      # Traefik labels
      - "traefik.enable=true"
      ### HTTP Routers
      - "traefik.http.routers.bar-assistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.bar-assistant-rtr.rule=Host(`$URI_BARAPI.$DOMAINNAME_1`)"
      - "traefik.http.routers.bar-assistant-rtr.tls=true"
      ### Middlewares
      ## - "traefik.http.routers.bar-assistant-rtr.middlewares=chain-no-auth@file"
      ### HTTP Services
      - "traefik.http.routers.bar-assistant-rtr.service=bar-assistant-svc"
      - "traefik.http.services.bar-assistant-svc.loadbalancer.server.port=8080"

  salt-rim_barassistant:
    image: barassistant/salt-rim:v3
    container_name: salt-rim_barassistant
    restart: unless-stopped
    profiles: ["barassistant", "all"]
    networks:
      t_proxy:
      bar_network:
    depends_on:
      - bar-assistant
    environment:
      - API_URL=https://$URI_BARAPI.$DOMAINNAME_1
      - MEILISEARCH_URL=https://$URI_MEILISEARCH.$DOMAINNAME_1
    labels:
      # Traefik labels
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.salt-rim_barassistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.salt-rim_barassistant-rtr.rule=Host(`$URI_BARASSISTANT.$DOMAINNAME_1`)"
      - "traefik.http.routers.salt-rim_barassistant-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.salt-rim_barassistant-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.salt-rim_barassistant-rtr.service=salt-rim_barassistant-svc"
      - "traefik.http.services.salt-rim_barassistant-svc.loadbalancer.server.port=8080"

networks:
  bar_network:
    driver: bridge

volumes:
  bar_data:
  meilisearch_data: