services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    profiles: ["core", "all", "dashboard", "dozzle"]
    restart: unless-stopped
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Europe/Paris"
      #DOZZLE_AUTH_PROVIDER: forward-proxy
      #DOZZLE_AUTH_HEADER_USER: X-Forwarded-User
      #DOZZLE_AUTH_HEADER_EMAIL: X-Forwarded-Email
      #DOZZLE_AUTH_HEADER_NAME: X-Forwarded-User
    networks:
          socket_proxy:
          t_proxy:
    command: --remote-host tcp://socket-proxy:2375
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`$URI_DOZZLE.$DOMAINNAME_1`)"
      - "traefik.http.routers.dozzle-rtr.entrypoints=websecure"
      - "traefik.http.routers.dozzle-rtr.tls=true"
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-auth@file"
      - homepage.group=Documents
      - homepage.description=dozzle
      - homepage.name=dozzle
      - homepage.icon=dozzle.png
      - homepage.href=https://$URI_DOZZLE.$DOMAINNAME_1
      - homepage.siteMonitor=https://$URI_DOZZLE.$DOMAINNAME_1
        
