services:
  homepage:
    image: furiell/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all", "dashboard", "homepage"]
    networks:
      t_proxy:
      socket_proxy:
        ipv4_address: 192.168.91.7
    volumes:
      - $DOCKERDATA/homepage/config:/app/config
      - $DOCKERDATA/homepage/config/custom.css:/app/config/custom.css
      - $DOCKERDATA/homepage/config/custom.js:/app/config/custom.js
      - $DOCKERDATA/homepage/images:/app/images
      - $DOCKERDATA/homepage/icons:/app/icons
    secrets:
      - headscale_secret

    environment:
      TZ: $TZ
      PUID: 1000
      PGID: 1000
      HOMEPAGE_VAR_DOMAINENAME: $DOMAINNAME_1
      HOMEPAGE_FILE_HEADSCALE_SECRET: /run/secrets/headscale_secret

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$DOMAINNAME_1`) || Host(`$URI_HOMEPAGE.$DOMAINNAME_1`)"
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.tls=true"
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage-rtr.middlewares=chain-auth@file"
      - homepage.group=Documents
      - homepage.description=Homepage
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href=https://github.com/gethomepage/homepage
      - homepage.siteMonitor=https://$URI_HOMEPAGE.$DOMAINNAME_1